"""Educational content: Ethical Hacking Academy, CTF challenges, Programming courses.
Bilingual (ar/en). Long, beginner-friendly lessons rendered by the bot."""

ACADEMY = [
    {
        "id": "recon",
        "title": {"ar": "🛰️ الاستطلاع وجمع المعلومات (OSINT)", "en": "🛰️ Reconnaissance & OSINT"},
        "lessons": [
            {"t": {"ar": "ما هو OSINT ولماذا هو أهم مرحلة؟", "en": "What is OSINT and why it matters"},
             "b": {"ar": "OSINT اختصار لـ Open-Source Intelligence، أي «الاستخبارات من المصادر المفتوحة». ببساطة شديدة: هو فن جمع المعلومات المتاحة للجميع علناً — مثل المواقع، سجلات النطاقات، حسابات التواصل العامة، البيانات المسربة المنشورة — وترتيبها لفهم «سطح الهجوم» لأي هدف.\n\nتخيّل أنك تريد اختبار أمان شركة (بإذنها). قبل أن تلمس أي شيء، تجمع كل ما هو معلن عنها: مواقعها، عناوين بريدها، خوادمها، الموظفين على LinkedIn. هذه المرحلة وحدها قد تكشف 70% من نقاط الضعف!\n\nالقاعدة الذهبية: اجمع فقط ما هو عام وقانوني، ولا تدخل أي نظام بدون إذن كتابي.",
                   "en": "OSINT stands for Open-Source Intelligence. Simply put: it's the art of collecting publicly available information — websites, domain records, public social accounts, published breach data — and organizing it to understand a target's 'attack surface'.\n\nImagine testing a company's security (with permission). Before touching anything, you gather everything public: their sites, email formats, servers, staff on LinkedIn. This phase alone can reveal 70% of weaknesses!\n\nGolden rule: only gather what is public and legal, and never enter any system without written authorization."}},
            {"t": {"ar": "الاستطلاع السلبي مقابل النشط", "en": "Passive vs Active recon"},
             "b": {"ar": "هناك نوعان من الاستطلاع:\n\n1) السلبي (Passive): تجمع معلومات دون أن يشعر الهدف أبداً. مثل قراءة موقعه، البحث في Google، فحص سجلات WHOIS و DNS. لا ترسل أي شيء مباشرة للهدف.\n\n2) النشط (Active): تتفاعل مباشرة مع أنظمة الهدف — مثل فحص المنافذ (port scanning) أو تعداد الخدمات. هنا قد تظهر في سجلاته.\n\nنصيحة المحترفين: ابدأ دائماً بالسلبي أولاً لتقليل أثرك، ثم انتقل للنشط فقط عند الحاجة وبإذن واضح.",
                   "en": "Two types of recon:\n\n1) Passive: gather info without the target ever noticing — reading their site, Google searches, WHOIS and DNS records. You send nothing directly to the target.\n\n2) Active: you interact directly with the target's systems — port scanning, service enumeration. This may appear in their logs.\n\nPro tip: always start passive to minimize your footprint, then move to active only when needed and with clear authorization."}},
            {"t": {"ar": "أدوات وتقنيات أساسية", "en": "Core tools & techniques"},
             "b": {"ar": "أهم الأدوات التي يستخدمها محترفو OSINT:\n\n• Google Dorks: استعلامات بحث متقدمة تكشف ملفات وصفحات مخفية (جرّب أداة Google Dorks في هذا البوت!).\n• theHarvester: يجمع الإيميلات والنطاقات الفرعية.\n• Shodan: محرك بحث للأجهزة المتصلة بالإنترنت.\n• Sherlock: يبحث عن اسم مستخدم عبر مئات المنصات (جرّب أداة بحث اسم المستخدم في البوت).\n• Amass: اكتشاف النطاقات الفرعية.\n\nكل أدوات هذا البوت (IP, WHOIS, DNS, Email Breach) هي أدوات OSINT حقيقية تطبّقها عملياً الآن.",
                   "en": "Top tools OSINT pros use:\n\n• Google Dorks: advanced search queries revealing hidden files/pages (try the Google Dorks tool in this bot!).\n• theHarvester: collects emails and subdomains.\n• Shodan: a search engine for internet-connected devices.\n• Sherlock: searches a username across hundreds of platforms (try the username tool here).\n• Amass: subdomain discovery.\n\nEvery tool in this bot (IP, WHOIS, DNS, Email Breach) is a real OSINT tool you can practice with right now."}},
        ],
    },
    {
        "id": "web",
        "title": {"ar": "🌐 أمن تطبيقات الويب (OWASP Top 10)", "en": "🌐 Web App Security (OWASP Top 10)"},
        "lessons": [
            {"t": {"ar": "حقن SQL (SQL Injection)", "en": "SQL Injection (SQLi)"},
             "b": {"ar": "SQL Injection من أخطر ثغرات الويب وأقدمها. تحدث عندما يأخذ الموقع مدخلات المستخدم ويضعها مباشرة داخل استعلام قاعدة البيانات دون تنقية.\n\nمثال مبسّط: لو كان تسجيل الدخول يبني الاستعلام هكذا:\nSELECT * FROM users WHERE name='INPUT'\nوأدخل المهاجم: ' OR '1'='1\nيصبح الشرط دائماً صحيحاً ويدخل بدون كلمة مرور!\n\nالوقاية: استخدم دائماً Prepared Statements (استعلامات مُعدّة مسبقاً) أو ORM، ولا تبنِ الاستعلام بدمج النصوص أبداً. تحقّق أيضاً من نوع المدخلات.",
                   "en": "SQL Injection is one of the oldest and most dangerous web flaws. It happens when a site takes user input and places it directly into a database query without sanitization.\n\nSimple example: if login builds the query as:\nSELECT * FROM users WHERE name='INPUT'\nand the attacker enters: ' OR '1'='1\nthe condition becomes always true and they log in without a password!\n\nFix: always use Prepared Statements or an ORM, never concatenate strings into queries. Also validate input types."}},
            {"t": {"ar": "XSS — البرمجة عبر المواقع", "en": "Cross-Site Scripting (XSS)"},
             "b": {"ar": "XSS تعني حقن كود JavaScript في صفحة يشاهدها مستخدمون آخرون، فيُنفَّذ في متصفحاتهم. يمكن للمهاجم سرقة الجلسات (cookies) أو تزوير الصفحة.\n\nمثال: حقل تعليقات لا يُنقّي المدخلات، فيكتب المهاجم:\n<script>alert('hacked')</script>\nوكل من يفتح الصفحة يُنفَّذ الكود عنده.\n\nأنواعها: Stored (مخزّن في الخادم)، Reflected (ينعكس من الرابط)، DOM-based.\n\nالوقاية: ترميز المخرجات (Output Encoding)، سياسة CSP، وتنقية كل مدخلات المستخدم قبل عرضها.",
                   "en": "XSS means injecting JavaScript into a page other users view, so it runs in their browsers. An attacker can steal sessions (cookies) or deface the page.\n\nExample: a comment field that doesn't sanitize input, attacker writes:\n<script>alert('hacked')</script>\nand anyone opening the page runs it.\n\nTypes: Stored (saved on server), Reflected (bounced from URL), DOM-based.\n\nFix: output encoding, a CSP policy, and sanitize all user input before rendering."}},
            {"t": {"ar": "IDOR والتحكم في الوصول", "en": "IDOR & Broken Access Control"},
             "b": {"ar": "IDOR اختصار Insecure Direct Object Reference. تحدث عندما تصل لموارد ليست لك بمجرد تغيير رقم في الرابط.\n\nمثال: تفتح فاتورتك على /invoice?id=123 ثم تغيّرها إلى id=124 فترى فاتورة شخص آخر! السبب أن الخادم لم يتحقق من صلاحيتك.\n\nهذا جزء من «كسر التحكم في الوصول» وهو رقم 1 في قائمة OWASP.\n\nالوقاية: تحقّق من الصلاحية على الخادم في كل طلب، ولا تعتمد على إخفاء الروابط فقط.",
                   "en": "IDOR = Insecure Direct Object Reference. It happens when you reach resources that aren't yours just by changing a number in the URL.\n\nExample: you open your invoice at /invoice?id=123, change it to id=124, and see someone else's invoice! Because the server didn't verify your authorization.\n\nThis is part of 'Broken Access Control', #1 on the OWASP list.\n\nFix: enforce server-side authorization on every request; never rely on hiding URLs."}},
            {"t": {"ar": "CSRF والمصادقة الضعيفة", "en": "CSRF & weak authentication"},
             "b": {"ar": "CSRF (تزوير الطلب عبر المواقع) يخدع متصفح الضحية لإرسال طلب لم يقصده، مستغلاً أنه مسجّل دخول. مثال: رابط خبيث ينفّذ «تحويل أموال» بينما أنت مسجّل في بنكك.\n\nالوقاية: رموز CSRF Tokens، وخاصية SameSite للكوكيز.\n\nأما المصادقة الضعيفة (كلمات مرور بسيطة، بدون تحقق بخطوتين) فهي باب واسع للاختراق. استخدم دائماً كلمات مرور قوية (جرّب مولّد كلمات المرور في البوت) وفعّل 2FA.",
                   "en": "CSRF (Cross-Site Request Forgery) tricks the victim's browser into sending an unintended request, abusing that they're logged in. Example: a malicious link performs a 'money transfer' while you're logged into your bank.\n\nFix: CSRF tokens and the SameSite cookie attribute.\n\nWeak authentication (simple passwords, no 2FA) is a wide-open door. Always use strong passwords (try the bot's generator) and enable 2FA."}},
        ],
    },
    {
        "id": "network",
        "title": {"ar": "📡 أساسيات الشبكات والفحص", "en": "📡 Networking & Scanning"},
        "lessons": [
            {"t": {"ar": "كيف يعمل الإنترنت: نموذج TCP/IP", "en": "How the internet works: TCP/IP"},
             "b": {"ar": "كل اتصال على الإنترنت يمر عبر طبقات:\n\n1) طبقة الوصول للشبكة (كابل/واي فاي).\n2) طبقة الإنترنت (IP): تعطي كل جهاز عنواناً وتوجّه الحزم.\n3) طبقة النقل (TCP/UDP): TCP موثوق ومرتّب (للمواقع)، UDP سريع بلا ضمان (للبث والألعاب).\n4) طبقة التطبيق (HTTP, DNS, SMTP): ما نتعامل معه مباشرة.\n\nفهم الطبقات يساعدك على تحليل الحزم، تشخيص المشاكل، وفهم أين يمكن أن يحدث الاختراق.",
                   "en": "Every internet connection passes through layers:\n\n1) Link layer (cable/Wi-Fi).\n2) Internet layer (IP): gives each device an address and routes packets.\n3) Transport layer (TCP/UDP): TCP is reliable and ordered (websites), UDP is fast without guarantees (streaming, games).\n4) Application layer (HTTP, DNS, SMTP): what we interact with directly.\n\nUnderstanding layers helps you analyze packets, troubleshoot, and see where attacks can happen."}},
            {"t": {"ar": "المنافذ والخدمات", "en": "Ports & services"},
             "b": {"ar": "كل خدمة على الخادم تستمع على «منفذ» (رقم من 0 إلى 65535). أشهرها:\n\n• 80 = HTTP\n• 443 = HTTPS\n• 22 = SSH\n• 21 = FTP\n• 25 = SMTP (بريد)\n• 53 = DNS\n• 3306 = MySQL\n\nعندما نفحص المنافذ نكتشف أي خدمات تعمل على هدف. منفذ مفتوح لخدمة قديمة = نقطة ضعف محتملة. (تذكّر تحدي CTF عن منفذ HTTPS الافتراضي!)",
                   "en": "Each server service listens on a 'port' (0–65535). The most common:\n\n• 80 = HTTP\n• 443 = HTTPS\n• 22 = SSH\n• 21 = FTP\n• 25 = SMTP (mail)\n• 53 = DNS\n• 3306 = MySQL\n\nScanning ports reveals which services run on a target. An open port to an outdated service = a potential weakness. (Recall the CTF about the default HTTPS port!)"}},
            {"t": {"ar": "فحص المنافذ بـ Nmap", "en": "Port scanning with Nmap"},
             "b": {"ar": "Nmap هو أشهر أداة فحص شبكات في العالم. أمثلة:\n\n• nmap 192.168.1.1 — فحص سريع للمنافذ الشائعة.\n• nmap -sV target — يكشف إصدارات الخدمات.\n• nmap -p- target — يفحص كل المنافذ (65535).\n• nmap -A target — فحص شامل (نظام التشغيل + الخدمات).\n\n⚠️ لا تفحص إلا أنظمة تملكها أو لديك إذن كتابي بفحصها. الفحص بدون إذن قد يُعدّ جريمة.",
                   "en": "Nmap is the world's most popular network scanner. Examples:\n\n• nmap 192.168.1.1 — quick scan of common ports.\n• nmap -sV target — detects service versions.\n• nmap -p- target — scans all 65535 ports.\n• nmap -A target — aggressive scan (OS + services).\n\n⚠️ Only scan systems you own or are authorized in writing to test. Unauthorized scanning can be a crime."}},
        ],
    },
    {
        "id": "crypto",
        "title": {"ar": "🔐 التشفير والتجزئة", "en": "🔐 Cryptography & Hashing"},
        "lessons": [
            {"t": {"ar": "التشفير المتماثل وغير المتماثل", "en": "Symmetric vs Asymmetric"},
             "b": {"ar": "التشفير نوعان:\n\n1) متماثل (Symmetric) مثل AES: مفتاح واحد للتشفير وفك التشفير. سريع جداً، لكن المشكلة: كيف تشارك المفتاح بأمان؟\n\n2) غير متماثل (Asymmetric) مثل RSA و ECC: زوج مفاتيح، عام (public) للتشفير وخاص (private) لفك التشفير. تنشر العام للجميع وتحتفظ بالخاص. يحل مشكلة تبادل المفاتيح.\n\nالواقع: بروتوكول HTTPS/TLS يجمع الاثنين — يستخدم غير المتماثل لتبادل مفتاح، ثم المتماثل للسرعة.",
                   "en": "Two kinds of encryption:\n\n1) Symmetric (e.g. AES): one key to encrypt and decrypt. Very fast, but: how do you share the key securely?\n\n2) Asymmetric (e.g. RSA, ECC): a key pair — public to encrypt, private to decrypt. You publish the public key and keep the private one. It solves the key-exchange problem.\n\nReality: HTTPS/TLS combines both — asymmetric to exchange a key, then symmetric for speed."}},
            {"t": {"ar": "التجزئة (Hashing) وحماية كلمات المرور", "en": "Hashing & password protection"},
             "b": {"ar": "التجزئة تحوّل أي نص إلى بصمة ثابتة الطول لا يمكن عكسها. تُستخدم للتحقق من السلامة وتخزين كلمات المرور.\n\nمهم جداً: لا تُخزّن كلمات المرور كنص واضح ولا بـ MD5 (ضعيف ومكسور). استخدم bcrypt أو argon2 مع «ملح» (salt) عشوائي لكل مستخدم — يمنع جداول الاختراق الجاهزة (rainbow tables).\n\nجرّب في البوت: أداة «مولّد Hash» لترى MD5/SHA، وأداة «كلمة مرور مسرّبة» لتفحص إن كانت كلمتك ظهرت في تسريبات.",
                   "en": "Hashing turns any text into a fixed-length fingerprint that can't be reversed. Used for integrity checks and storing passwords.\n\nCritical: never store passwords as plaintext or with MD5 (weak and broken). Use bcrypt or argon2 with a random per-user 'salt' — it defeats precomputed rainbow tables.\n\nTry in the bot: 'Hash Generator' to see MD5/SHA, and 'Pwned Password' to check if your password appeared in breaches."}},
        ],
    },
    {
        "id": "linux",
        "title": {"ar": "🐧 لينكس للهاكر الأخلاقي", "en": "🐧 Linux for Ethical Hackers"},
        "lessons": [
            {"t": {"ar": "لماذا لينكس؟ وأوامر أساسية", "en": "Why Linux? + essential commands"},
             "b": {"ar": "معظم الخوادم والأدوات الأمنية تعمل على لينكس، ولهذا يتقنه كل خبير أمن. توزيعة Kali Linux مبنية خصيصاً لاختبار الاختراق.\n\nأوامر يجب أن تحفظها:\n• ls — عرض الملفات\n• cd — التنقل بين المجلدات\n• pwd — مكانك الحالي\n• cat — عرض محتوى ملف\n• grep — البحث داخل النصوص\n• find — البحث عن ملفات\n• chmod — تغيير الصلاحيات\n• ps / top — العمليات النشطة\n• netstat / ss — الاتصالات الشبكية\n\nتدرّب عليها يومياً حتى تصبح طبيعية.",
                   "en": "Most servers and security tools run on Linux, which is why every security pro masters it. Kali Linux is a distro built specifically for penetration testing.\n\nCommands to memorize:\n• ls — list files\n• cd — navigate folders\n• pwd — current location\n• cat — show file content\n• grep — search inside text\n• find — locate files\n• chmod — change permissions\n• ps / top — running processes\n• netstat / ss — network connections\n\nPractice daily until they feel natural."}},
            {"t": {"ar": "الصلاحيات وتصعيد الامتيازات", "en": "Permissions & privilege escalation"},
             "b": {"ar": "في لينكس لكل ملف صلاحيات: قراءة (r)، كتابة (w)، تنفيذ (x)، لثلاث فئات: المالك، المجموعة، الآخرين. تراها بـ ls -l مثل: -rwxr-xr--\n\nمفهوم مهم في الاختراق: تصعيد الامتيازات (Privilege Escalation) — أن تبدأ كمستخدم عادي وتصل لصلاحيات root. من أشهر الطرق: ملفات SUID خاطئة الإعداد، أو خدمات تعمل بصلاحيات عالية.\n\nفي تحديات CTF، فهم rwx و SUID غالباً هو مفتاح الوصول لعلم النهاية.",
                   "en": "In Linux, every file has permissions: read (r), write (w), execute (x), for three classes: owner, group, others. See them with ls -l like: -rwxr-xr--\n\nA key hacking concept: Privilege Escalation — start as a normal user and reach root. Common paths: misconfigured SUID files, or services running with high privileges.\n\nIn CTF challenges, understanding rwx and SUID is often the key to the final flag."}},
        ],
    },
]

CTF = [
    {"id": "c1", "points": 50, "cat": {"ar": "تشفير", "en": "Crypto"},
     "title": {"ar": "قيصر البسيط", "en": "Simple Caesar"},
     "q": {"ar": "فك تشفير النص (إزاحة 3 للخلف): <code>FODJ{fdhvdu_lv_hdvb}</code>\nأرسل العلم كاملاً.",
           "en": "Decrypt (shift 3 back): <code>FODJ{fdhvdu_lv_hdvb}</code>\nSend the full flag."},
     "flag": "FLAG{caesar_is_easy}"},
    {"id": "c2", "points": 60, "cat": {"ar": "ترميز", "en": "Encoding"},
     "title": {"ar": "مخفي بالـ Base64", "en": "Hidden in Base64"},
     "q": {"ar": "فك الترميز (استخدم أداة Base64 بالبوت): <code>RkxBR3tiNjRfZGVjb2RlZH0=</code>", "en": "Decode (use the bot's Base64 tool): <code>RkxBR3tiNjRfZGVjb2RlZH0=</code>"},
     "flag": "FLAG{b64_decoded}"},
    {"id": "c3", "points": 80, "cat": {"ar": "ويب", "en": "Web"},
     "title": {"ar": "روبوتس", "en": "Robots"},
     "q": {"ar": "أي ملف يخبر محركات البحث بما لا تفهرسه وكثيراً ما يكشف مسارات مخفية؟ الصيغة: FLAG{اسم_الملف}",
           "en": "Which file tells search engines what not to index and often leaks hidden paths? Format: FLAG{filename}"},
     "flag": "FLAG{robots.txt}"},
    {"id": "c4", "points": 70, "cat": {"ar": "تجزئة", "en": "Hashing"},
     "title": {"ar": "تعرّف عليّ", "en": "Identify me"},
     "q": {"ar": "ما نوع هذه البصمة؟ (استخدم أداة تحديد Hash) <code>5f4dcc3b5aa765d61d8327deb882cf99</code>\nالصيغة: FLAG{النوع}",
           "en": "What hash type is <code>5f4dcc3b5aa765d61d8327deb882cf99</code>? (use the Hash ID tool)\nFormat: FLAG{type}"},
     "flag": "FLAG{md5}"},
    {"id": "c5", "points": 90, "cat": {"ar": "شبكات", "en": "Networking"},
     "title": {"ar": "المنفذ الافتراضي", "en": "Default port"},
     "q": {"ar": "ما المنفذ الافتراضي لـ HTTPS؟ الصيغة: FLAG{الرقم}", "en": "Default HTTPS port? Format: FLAG{number}"},
     "flag": "FLAG{443}"},
    {"id": "c6", "points": 100, "cat": {"ar": "OSINT", "en": "OSINT"},
     "title": {"ar": "من يملك النطاق", "en": "Who owns it"},
     "q": {"ar": "أي بروتوكول/سجل تستعلم به عن مالك نطاق وتاريخ تسجيله؟ الصيغة: FLAG{الاسم}",
           "en": "Which record/protocol do you query for a domain's owner and registration date? Format: FLAG{name}"},
     "flag": "FLAG{whois}"},
    {"id": "c7", "points": 110, "cat": {"ar": "ويب", "en": "Web"},
     "title": {"ar": "الحقن الكلاسيكي", "en": "Classic injection"},
     "q": {"ar": "ما اسم الثغرة التي تسمح بإدخال أوامر قاعدة بيانات عبر حقول الإدخال؟ الصيغة: FLAG{الاختصار} (3 أحرف)",
           "en": "Name the flaw allowing database commands via input fields. Format: FLAG{abbr} (3 letters)"},
     "flag": "FLAG{sql}"},
    {"id": "c8", "points": 120, "cat": {"ar": "تشفير", "en": "Crypto"},
     "title": {"ar": "الست عشري", "en": "Hex speak"},
     "q": {"ar": "حوّل من hex: <code>464c41477b6865785f6d61737465727d</code>", "en": "Convert from hex: <code>464c41477b6865785f6d61737465727d</code>"},
     "flag": "FLAG{hex_master}"},
]

COURSES = [
    {
        "id": "py",
        "title": {"ar": "🐍 بايثون من الصفر للاحتراف", "en": "🐍 Python: Zero to Pro"},
        "lessons": [
            {"t": {"ar": "مقدمة: لماذا بايثون؟", "en": "Intro: why Python?"},
             "b": {"ar": "بايثون أسهل لغة برمجة للمبتدئين وأقواها للمحترفين. تُستخدم في الأمن السيبراني، الذكاء الاصطناعي، تحليل البيانات، والمواقع.\n\nمميزاتها:\n• كودها يشبه الإنجليزية، سهل القراءة.\n• مكتبات جاهزة لكل شيء تقريباً.\n• مطلوبة بشدة في سوق العمل.\n\nكل ما تحتاجه للبدء: تثبيت Python من python.org ومحرر مثل VS Code. في هذه الدورة ستتعلم خطوة بخطوة من الصفر.",
                   "en": "Python is the easiest language for beginners and one of the most powerful for pros. Used in cybersecurity, AI, data analysis, and web.\n\nStrengths:\n• Code reads like English.\n• Ready-made libraries for almost everything.\n• In high demand in the job market.\n\nAll you need to start: install Python from python.org and an editor like VS Code. This course teaches you step by step from zero."}},
            {"t": {"ar": "المتغيرات وأنواع البيانات", "en": "Variables & data types"},
             "b": {"ar": "المتغيّر صندوق يخزّن قيمة. بايثون تحدد النوع تلقائياً:\n\n<code>name = \"Ali\"      # نص (str)\nage = 20          # عدد صحيح (int)\nprice = 9.99      # عدد عشري (float)\nis_admin = True   # منطقي (bool)</code>\n\nلطباعة قيمة: <code>print(name)</code>\nلمعرفة النوع: <code>type(age)</code>\n\nنصيحة: اختر أسماء متغيّرات واضحة تصف محتواها.",
                   "en": "A variable is a box storing a value. Python infers the type:\n\n<code>name = \"Ali\"      # string (str)\nage = 20          # integer (int)\nprice = 9.99      # float\nis_admin = True   # boolean (bool)</code>\n\nTo print: <code>print(name)</code>\nTo check the type: <code>type(age)</code>\n\nTip: choose clear variable names that describe their content."}},
            {"t": {"ar": "العمليات والنصوص", "en": "Operations & strings"},
             "b": {"ar": "العمليات الحسابية: + - * / و ** للأس و % لباقي القسمة.\n\nمع النصوص:\n<code>first = \"Cyber\"\nsecond = \"Sec\"\nprint(first + second)   # CyberSec\nprint(first * 2)         # CyberCyber\nprint(len(first))        # 5\nprint(first.upper())     # CYBER</code>\n\nالـ f-string طريقة أنيقة للدمج:\n<code>print(f\"عمري {age} سنة\")</code>",
                   "en": "Arithmetic: + - * / , ** for power, % for remainder.\n\nWith strings:\n<code>first = \"Cyber\"\nsecond = \"Sec\"\nprint(first + second)   # CyberSec\nprint(first * 2)         # CyberCyber\nprint(len(first))        # 5\nprint(first.upper())     # CYBER</code>\n\nf-strings are an elegant way to combine:\n<code>print(f\"I am {age} years old\")</code>"}},
            {"t": {"ar": "الشروط (if / else)", "en": "Conditions (if / else)"},
             "b": {"ar": "الشروط تجعل البرنامج يتخذ قرارات:\n\n<code>age = 18\nif age >= 18:\n    print(\"بالغ\")\nelif age >= 13:\n    print(\"مراهق\")\nelse:\n    print(\"طفل\")</code>\n\nالمقارنات: == يساوي، != لا يساوي، > < >= <=\nالمنطق: and, or, not\n\nانتبه للمسافات البادئة (indentation) — بايثون تعتمد عليها لتحديد الكتل.",
                   "en": "Conditions let the program make decisions:\n\n<code>age = 18\nif age >= 18:\n    print(\"adult\")\nelif age >= 13:\n    print(\"teen\")\nelse:\n    print(\"child\")</code>\n\nComparisons: == equals, != not equals, > < >= <=\nLogic: and, or, not\n\nMind the indentation — Python uses it to define blocks."}},
            {"t": {"ar": "الحلقات (for / while)", "en": "Loops (for / while)"},
             "b": {"ar": "الحلقات تكرّر العمل:\n\n<code>for i in range(5):\n    print(i)   # 0 1 2 3 4\n\nnames = [\"Ali\", \"Sara\"]\nfor n in names:\n    print(n)\n\ncount = 0\nwhile count < 3:\n    print(count)\n    count += 1</code>\n\nكلمات مفيدة: break للخروج، continue لتخطي دورة.",
                   "en": "Loops repeat work:\n\n<code>for i in range(5):\n    print(i)   # 0 1 2 3 4\n\nnames = [\"Ali\", \"Sara\"]\nfor n in names:\n    print(n)\n\ncount = 0\nwhile count < 3:\n    print(count)\n    count += 1</code>\n\nUseful keywords: break to exit, continue to skip an iteration."}},
            {"t": {"ar": "القوائم والقواميس", "en": "Lists & dictionaries"},
             "b": {"ar": "القائمة (list) تخزّن عدة قيم مرتّبة:\n<code>fruits = [\"apple\", \"banana\"]\nfruits.append(\"mango\")\nprint(fruits[0])   # apple</code>\n\nالقاموس (dict) يخزّن أزواج مفتاح-قيمة:\n<code>user = {\"name\": \"Ali\", \"age\": 20}\nprint(user[\"name\"])   # Ali\nuser[\"city\"] = \"Baghdad\"</code>\n\nهذان النوعان أساس معظم البرامج الحقيقية.",
                   "en": "A list stores several ordered values:\n<code>fruits = [\"apple\", \"banana\"]\nfruits.append(\"mango\")\nprint(fruits[0])   # apple</code>\n\nA dictionary stores key-value pairs:\n<code>user = {\"name\": \"Ali\", \"age\": 20}\nprint(user[\"name\"])   # Ali\nuser[\"city\"] = \"Baghdad\"</code>\n\nThese two types are the backbone of most real programs."}},
            {"t": {"ar": "الدوال (Functions)", "en": "Functions"},
             "b": {"ar": "الدالة كتلة كود قابلة لإعادة الاستخدام:\n\n<code>def greet(name):\n    return f\"مرحبا {name}\"\n\nmsg = greet(\"Ali\")\nprint(msg)   # مرحبا Ali</code>\n\nيمكن أن تأخذ عدة مدخلات وقيم افتراضية:\n<code>def add(a, b=0):\n    return a + b</code>\n\nالدوال تنظّم الكود وتمنع التكرار — قاعدة DRY: لا تكرّر نفسك.",
                   "en": "A function is a reusable block of code:\n\n<code>def greet(name):\n    return f\"Hello {name}\"\n\nmsg = greet(\"Ali\")\nprint(msg)   # Hello Ali</code>\n\nIt can take several inputs and defaults:\n<code>def add(a, b=0):\n    return a + b</code>\n\nFunctions organize code and prevent repetition — the DRY rule: Don't Repeat Yourself."}},
            {"t": {"ar": "مشروع صغير: أداة أمنية بسيطة", "en": "Mini project: a tiny security tool"},
             "b": {"ar": "لنجمع ما تعلمناه في أداة تفحص قوة كلمة المرور:\n\n<code>def check(pw):\n    score = 0\n    if len(pw) >= 8: score += 1\n    if any(c.isdigit() for c in pw): score += 1\n    if any(c.isupper() for c in pw): score += 1\n    if any(not c.isalnum() for c in pw): score += 1\n    return score\n\npw = input(\"أدخل كلمة مرور: \")\nprint(\"القوة:\", check(pw), \"/4\")</code>\n\nهذا بالضبط منطق مشابه لأداة كلمات المرور في هذا البوت! كمّل التعلم بمكتبة requests للتعامل مع الإنترنت.",
                   "en": "Let's combine what we learned into a password-strength checker:\n\n<code>def check(pw):\n    score = 0\n    if len(pw) >= 8: score += 1\n    if any(c.isdigit() for c in pw): score += 1\n    if any(c.isupper() for c in pw): score += 1\n    if any(not c.isalnum() for c in pw): score += 1\n    return score\n\npw = input(\"Enter a password: \")\nprint(\"Strength:\", check(pw), \"/4\")</code>\n\nThis is exactly the kind of logic behind this bot's password tool! Continue with the requests library to work with the internet."}},
        ],
    },
    {
        "id": "js",
        "title": {"ar": "🟨 جافاسكربت للمبتدئين", "en": "🟨 JavaScript Basics"},
        "lessons": [
            {"t": {"ar": "ما هي جافاسكربت؟", "en": "What is JavaScript?"},
             "b": {"ar": "جافاسكربت هي لغة الويب: تجعل الصفحات تفاعلية (أزرار، نماذج، حركة). تعمل داخل كل متصفح، ومع Node.js تعمل على الخوادم أيضاً.\n\nتكتبها داخل HTML بين وسمي <script> أو في ملف .js منفصل. افتح Console في متصفحك (F12) وجرّب:\n<code>console.log(\"مرحبا بالعالم\");</code>",
                   "en": "JavaScript is the language of the web: it makes pages interactive (buttons, forms, motion). It runs in every browser, and with Node.js on servers too.\n\nYou write it inside HTML between <script> tags or in a separate .js file. Open your browser Console (F12) and try:\n<code>console.log(\"Hello world\");</code>"}},
            {"t": {"ar": "المتغيرات والأنواع", "en": "Variables & types"},
             "b": {"ar": "<code>let x = 5;        // متغيّر يتغيّر\nconst PI = 3.14;  // ثابت لا يتغيّر\nvar old = 1;      // قديم، تجنّبه</code>\n\nالأنواع: number, string, boolean, array, object.\n<code>let user = { name: \"Ali\", age: 20 };\nlet list = [1, 2, 3];\nconsole.log(user.name, list[0]);</code>",
                   "en": "<code>let x = 5;        // a changeable variable\nconst PI = 3.14;  // a constant\nvar old = 1;      // old, avoid it</code>\n\nTypes: number, string, boolean, array, object.\n<code>let user = { name: \"Ali\", age: 20 };\nlet list = [1, 2, 3];\nconsole.log(user.name, list[0]);</code>"}},
            {"t": {"ar": "الدوال والدوال السهمية", "en": "Functions & arrow functions"},
             "b": {"ar": "الطريقة التقليدية:\n<code>function add(a, b) {\n  return a + b;\n}</code>\n\nالدالة السهمية (أحدث وأقصر):\n<code>const add = (a, b) => a + b;\nconsole.log(add(2, 3)); // 5</code>\n\nالدوال السهمية شائعة جداً في React والكود الحديث.",
                   "en": "Traditional way:\n<code>function add(a, b) {\n  return a + b;\n}</code>\n\nArrow function (newer, shorter):\n<code>const add = (a, b) => a + b;\nconsole.log(add(2, 3)); // 5</code>\n\nArrow functions are very common in React and modern code."}},
            {"t": {"ar": "التفاعل مع الصفحة (DOM)", "en": "Interacting with the page (DOM)"},
             "b": {"ar": "الـ DOM هو تمثيل الصفحة الذي يمكن لجافاسكربت تعديله:\n\n<code>const btn = document.querySelector(\"#myBtn\");\nbtn.addEventListener(\"click\", () => {\n  alert(\"تم الضغط!\");\n});</code>\n\nبهذا تجعل الأزرار والنماذج حيّة. هذا أساس أي واجهة تفاعلية.",
                   "en": "The DOM is the page representation JS can modify:\n\n<code>const btn = document.querySelector(\"#myBtn\");\nbtn.addEventListener(\"click\", () => {\n  alert(\"Clicked!\");\n});</code>\n\nThat's how you make buttons and forms alive — the basis of any interactive UI."}},
        ],
    },
    {
        "id": "bash",
        "title": {"ar": "💻 Bash والأتمتة", "en": "💻 Bash & Automation"},
        "lessons": [
            {"t": {"ar": "أول سكربت Bash", "en": "Your first Bash script"},
             "b": {"ar": "Bash لغة سطر الأوامر في لينكس، رائعة للأتمتة. أنشئ ملف script.sh:\n\n<code>#!/bin/bash\necho \"مرحبا $USER\"\ndate</code>\n\nثم اجعله قابلاً للتنفيذ وشغّله:\n<code>chmod +x script.sh\n./script.sh</code>\n\nالسطر الأول (#!/bin/bash) يخبر النظام أي مفسّر يستخدم.",
                   "en": "Bash is the Linux command-line language, great for automation. Create script.sh:\n\n<code>#!/bin/bash\necho \"Hello $USER\"\ndate</code>\n\nThen make it executable and run it:\n<code>chmod +x script.sh\n./script.sh</code>\n\nThe first line (#!/bin/bash) tells the system which interpreter to use."}},
            {"t": {"ar": "المتغيرات والحلقات في Bash", "en": "Variables & loops in Bash"},
             "b": {"ar": "<code>#!/bin/bash\nname=\"Ali\"\necho \"Hi $name\"\n\nfor i in 1 2 3; do\n  echo \"Number $i\"\ndone\n\nfor f in *.txt; do\n  echo \"Found: $f\"\ndone</code>\n\nبهذا تعالج ملفات كثيرة تلقائياً — مهارة أساسية لأي خبير أمن.",
                   "en": "<code>#!/bin/bash\nname=\"Ali\"\necho \"Hi $name\"\n\nfor i in 1 2 3; do\n  echo \"Number $i\"\ndone\n\nfor f in *.txt; do\n  echo \"Found: $f\"\ndone</code>\n\nThis lets you process many files automatically — a core skill for any security pro."}},
        ],
    },
    {
        "id": "sec",
        "title": {"ar": "🛡️ مقدمة الأمن السيبراني", "en": "🛡️ Cybersecurity Intro"},
        "lessons": [
            {"t": {"ar": "ثالوث CIA", "en": "The CIA triad"},
             "b": {"ar": "كل الأمن السيبراني يقوم على ثلاثة أعمدة (CIA):\n\n1) السرية (Confidentiality): وصول المعلومة للمصرّح لهم فقط — بالتشفير والصلاحيات.\n2) السلامة (Integrity): ألا تُعدَّل البيانات دون إذن — بالتجزئة والتواقيع الرقمية.\n3) التوفّر (Availability): أن تبقى الخدمة متاحة — بالحماية من هجمات DDoS والنسخ الاحتياطي.\n\nأي هجوم يستهدف واحداً أو أكثر من هذه الأعمدة.",
                   "en": "All cybersecurity rests on three pillars (CIA):\n\n1) Confidentiality: info reaches only the authorized — via encryption and permissions.\n2) Integrity: data isn't altered without authorization — via hashing and digital signatures.\n3) Availability: the service stays reachable — via DDoS protection and backups.\n\nEvery attack targets one or more of these pillars."}},
            {"t": {"ar": "أنواع التهديدات الشائعة", "en": "Common threat types"},
             "b": {"ar": "تعرّف على أعدائك:\n\n• التصيّد (Phishing): رسائل مزيّفة تسرق بياناتك (استخدم فاحص الروابط بالبوت!).\n• البرمجيات الخبيثة (Malware): فيروسات، فدية، برامج تجسّس.\n• هندسة اجتماعية: خداع البشر للحصول على معلومات.\n• هجوم القوة الغاشمة: تجربة كلمات مرور كثيرة.\n• هجمات الوسيط (MITM): التنصّت على الاتصال.\n\nالدفاع يبدأ بالوعي: كلمات مرور قوية، 2FA، تحديثات، وعدم الضغط على روابط مشبوهة.",
                   "en": "Know your enemies:\n\n• Phishing: fake messages stealing your data (use the bot's URL scanner!).\n• Malware: viruses, ransomware, spyware.\n• Social engineering: tricking humans for info.\n• Brute force: trying many passwords.\n• MITM: eavesdropping on a connection.\n\nDefense starts with awareness: strong passwords, 2FA, updates, and not clicking suspicious links."}},
            {"t": {"ar": "أخلاقيات الاختراق والقانون", "en": "Hacking ethics & the law"},
             "b": {"ar": "الفرق بين الهاكر الأخلاقي والمجرم ليس المهارة، بل الإذن والنية والقانون:\n\n• القبعة البيضاء (White Hat): يخترق بإذن لحماية الأنظمة، وغالباً بوظيفة رسمية.\n• القبعة السوداء (Black Hat): يخترق بشكل غير قانوني للضرر أو المكسب.\n• القبعة الرمادية: بينهما، وقد يقع في مشاكل قانونية.\n\nالقاعدة الحاسمة: لا تختبر أي نظام لا تملكه بدون إذن كتابي صريح. حتى الفحص البسيط قد يُعدّ جريمة. تعلّم عبر منصات قانونية مثل TryHackMe و HackTheBox و CTF.",
                   "en": "The difference between an ethical hacker and a criminal isn't skill — it's permission, intent, and law:\n\n• White Hat: hacks with permission to protect systems, often as a job.\n• Black Hat: hacks illegally for harm or gain.\n• Grey Hat: in between, and can land in legal trouble.\n\nThe decisive rule: never test any system you don't own without explicit written authorization. Even a simple scan can be a crime. Learn on legal platforms like TryHackMe, HackTheBox, and CTFs."}},
        ],
    },
]
